apiVersion: v2
name: ical-filter-proxy
description: iCal proxy with support for user-defined filtering rules
type: application
# Release publishing overwrites version and appVersion for tagged builds.
version: 0.0.0
appVersion: "unreleased"
maintainers:
  - name: yungwood
