name: go-test

on:
  push:
    branches:
      - "*"
    paths:
      - go.mod
      - go.sum
      - "*.go"
  pull_request:
    paths:
      - go.mod
      - go.sum
      - "*.go"

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: go test
        run: go test ./...
